# Sample .travis.yml for R projects.
# 
# See README.md for instructions.
# adapted from: https://github.com/jokergoo/ComplexHeatmap/blob/master/.travis.yml

language: r

sudo: required

r-packages:
- fgui
- stringr
- plyr
- epiR
- RColorBrewer
- scales
- drc
- foreach
- DoseFinding
- knitr
- rmarkdown
- ggplot2
- grid



after_success:
  - Rscript -e 'library(covr);codecov()'

after_failure:
  - ./travis-tool.sh dump_logs

# Configuration options below this line are suggested options.
notifications:
  email:
    on_success: change
    on_failure: change
